const astarionLines = [
    "Trust no one.",
    "Careful. I bite.",
    "Watch your back.",
    "Keep a blade close.",
    "Looking at something?",
    "On your knees, darling.",
    "I will have to decline.",
    "Gods, you're beautiful.",
    "Don't flatter yourself.",
    "Never say never, darling.",
    "You little scoundrel, you.",
    "Do you mind? I'm brooding.",
    "Precious little Bhaal-babe!",
    "Keep your distance, darling.",
    "Exquisite. Simply exquisite.",
    "What a delectable little pet.",
    "I'm all pointy ears, my love.",
    "Come to kill me again, darling?",
    "Stop bleeding. It's distracting.", // LMFAO O K A Y
    "But you're my leaking blood bag.",
    "Ah ah ah! We ask before we bite.",
    "Erm, yes. It does smell the part.",
    "Shhh. Just think sneaky thoughts.",
    "Well, at least you purr for me...",
    "Ooh, I do so very like spicy food.",
    "Ha! Well, when you look this good...",
    "Looking perfect as always. I assume.",
    "'Us'. I still love the sound of that.",
    "I can't be what you want to see in me.",
    "Ask me anything, and it will be yours.",
    "I must see this. Don't you dare say no.",
    "Please, don't mind me. I'll just watch.",
    "This thing won't have you. It won't win.",
    "You have given me everything. Thank you.",
    "Can we kill them? Please? Pretty please?",
    "It's not you, it's me. I have standards!",
    "Be very, very quiet. I'm hunting idiots.",
    "Is it true? You've decided to replace me?",
    "Guilty as charged. Sometimes literally...",
    "My dagger-happy friend, what troubles you?",
    "As a person? Would that be so much to ask?",
    "Little love, whatever could be the matter?",
    "Really? I prefer my company extraordinary.",
    "Easy now, let's not do anything hilarious.",
    "Do you always take on such terrifying foes?",
    "This is a gift, you know. I won’t forget it.",
    "You villain! I didn't know you had it in you.",
    "Poor beast. It probably only wanted a cuddle.",
    "You're staring at me again. What do you want?",
    "Enough sitting around - let's go hurt someone.",
    "I hope there's nothing troubling you, my dear?",
    "You always pick the most romantic spots to chat.",
    "No! He's not eating this one. It's too valuable.",
    "Oh now look, you've scared off the little snack.",
    "So Gale, how is your sad, hopeless pining going?",
    "I hear you did the deed. How was your little romp?",
    "Hrmmm. Thank you for helping me. It was very kind.",
    "Is there something you want to talk about, my dear?",
    "Of course, what fun! I'm going to fucking kill you.",
    "Easy now darling. You’ve got this, And I’ve got you.",
    "My sweet, conflicted villain. What can I do for you?",
    "Absolutely not. We've hit our quota for mangy strays.",
    "Well, I mean... kind of? It's a long story, honestly.",
    "What a mess. Well, at least you've met my family now.",
    "Then come with me, my love, and live your final night.",
    "I don't need a reflection to know this looks fabulous.",
    "'Spawn' is an ugly word. I really do prefer 'consort'.",
    "I should've been a drow. They have such stylish armour.",
    "Gods above. Would it kill you to dispense a compliment?", 
    "How did I go two hundred years without seeing that face?",
    "All right, time to see what new horror's waiting for us.",
    "Ah, you're so adorable when you're thinking what to say.",
    "Are you now? Don't make promises you can't keep, darling.",
    "Adorable. Let me know when it brings you something fresh.",
    "Naturally, I always ask first. I'm civilised, unlike you.",
    "They said 'no'. You should learn the meaning of the word.",
    "Look at you, precious thing. You always stare so eagerly.",
    "I'm all for blood, but a whole lake? That's just wasteful.",
    "Someone's ready to fight. Oh, I do hope it's to the death.",
    "Oh shit. I - did I do something wrong? Why? What's changed?",
    "If you're trying to encourage me, you're failing abysmally.",
    "Oh she doesn't bother me that much. If anything, I pity her.",
    "No! No, fuck you and fuck everything you've ever done to me.",
    "You're not going to eviscerate him? I was hoping for a show.",
    "Oh - you meant 'be kinder'. Pet bunnies, that sort of thing?",
    "Oh that's grotesque. Don't stare - you'll only encourage it.",
    "You brought my dead heart back to life. It will keep beating.",
    "Strange little beast. I would've made short work of it, once.",
    "You couldn't wait ten seconds before being an absolute freak?",
    "Since when has yielding been an option? Gut the little rodent.",
    "Eugh, don't be so nice to me! It makes me want to be nice back.",
    "Oh, pardon. I'll leave you to drop dead in your own time, then.",
    "Wait! Don't interrupt them. Let me do it. They sound disgusting.",
    "Oh good, puns. Because clowns aren't enough of a horror already.",
    "Don't worry, we're all friends under the Absolute. I won't bite.",
    "Does... Does that count as us killing him? That had better count.",
    "I have one person who trusts me completely. That's enough for me.",
    "Ageing? What do you mean 'ageing'? I'm a vampire - forever young.",
    "So... are you greeting invisible beings or just losing your mind?",
    "Yes dear, I can see that you killed her. But why did you kill her?",
    "We'd better survive this, because I never want to stop doing that.",
    "You're cute, you know. In another life we might have been friends.",
    "Only when it comes to morals. I'm very, very good where it counts.",
    "My consort, we are so close to our triumph, I can almost taste it.",
    "You sweet, sweet thing. I want what's best for you too, of course.",
    "Growl all you want, it won't stop the dawn. This will be over soon.",
    "You have a manner of irresistible desperation about you. I like it.",
    "Urgh. That body's so ripe, I'd need to drink the blood with a fork.",
    "I haven't spent much time with helpless old ladies. Was that normal?",
    "Good, because selfless as I am, I really did not want to let you go.",
    "Well, death never stopped me before. I don't know why it should now.",
    "We shouldn't be involved with each other any more. I'll sleep alone.",
    "Tailors' mannequins? I never figured Shar for a follower of fashion.",
    "Shh. Not a sound. Not if you want to keep that darling neck of yours.",
    "Don't be touchy. I'm sure he meant 'better off dead' as a compliment.",
    "You look drained, and I know it wasn't me. Is the plant bothering you?",
    "Ha! Defeating a devil in his own home feels very, very good, actually.",
    "Trading some whelp we just met for impossible power? It's a fine deal.",
    "Don't hate me. I just did what I had to. I swear, I did what I had to.", // .... damn .... 
    "I admit, I like this one's approach. A little genocidal, but effective.",
    "What a pretty thing. I imagine it's dangerous - most pretty things are.",
    "I'm not afraid. Not of you, not of your darkness, and not of our future.",
    "If they ask for a sacrifice, I'd suggest virgins. Young and hot-blooded.",
    "Why she sounds positively demented. I love it! Let's tell her everything.",
    "Oh, I'm well aware of what the master needs. But don't we deserve better?",
    "Ah, nothing says 'true love' like faking your own death to avoid someone.",
    "Now shall we go? Or do you have any other chaos you need to unleash here?",
    "Aside from my once-beautiful lover turning into a monster? Oh, wonderful.",
    "It is dangerous, wandering around at night. You could bump into anything.",
    "The norm is to keep dirty thoughts like that to ourselves. But do carry on.",
    "I hear things got wild between you two. I hope no one was too badly mauled.",
    "Five seconds into this relationship and I already want to break up with you.",
    "Just a look. And if we don't like what we see, we can always kill her later.",
    "What did you think I was going to say? 'Oh, come here, I'll kiss you better'?",
    "You sound surprised. I am capable of doing the right thing from time to time.",
    "Well, this seems like a lovely little spot. The sense of impending doom aside.",
    "I do appreciate your enthusiasm, but let's try to restrain ourselves a little.",
    "Nothing special, of course. You're only the first person who I truly care for.",
    "Breaking into druid chambers to steal a sacred relic? Oh, she sounds like fun.",   
    "You look rabid, pained, sick. You are spasming and twitching... You poor thing.",
    "What are you doing? That had better go down the drain and not down your gullet.",
    "So, we're travelling with the famed 'Blade of Frontiers'. I feel safer already.",
    "It does sound divine. You'll have to catch me up on all the gory details later.",
    "Say no. The only thing she's offering is pain and I don't want to see you hurt.",
    "The thing that will decide my fate forevermore? Yes, it's been on my mind - why?",
    "You're welcome to try and kill me, of course, but I don't die easily these days.",
    "I'd rather be the only dark power inside your body, if it's all the same to you.",
    "When he says 'punished' do you think he means 'locked up' or 'brutally murdered'?",
    "You are not alone in this. None of us are. We can even compare notes if you like.",
    "Are you really being waylaid by a snack? Let's just look around, vermin be damned.",
    "Hundreds? Urgh, it'll take hours to kill them all. She's right, we should just go.",
    "There's a time for talking and a time for killing. This, my friend, is the latter.",
    "You want to just team up with some blood-stained killer? Because I'm fine with that.",
    "Flowers are so overrated. They're bright, gaudy, and almost never make good poisons.",
    "She probably just needs some time for it to sink in. I'm sure she'll be elated soon.",
    "Marriage, Wyll? I thought you'd have learned not to get trapped by devious contracts.",
    "You gave me precious, impossible moments of comfort. I only really wanted a few more.",
    "All right sweethearts. You dare to dance with a professional, you'll get your desire.",
    "I realise now I've never really had anyone. Not really. Nothing that compares to you.",
    "You have a type, don't you? Elven prostitutes? Again? It's rather embarrassing, dear.",
    "I felt for the bard, seeing you like that. Poor Alfira never stood a chance, did she?",
    "A shapeshifter? It could be anyone. I mean - it's not me, but it could be anyone else.",
    "And I will keep refusing until the end of time. I'm done bowing to the whims of others.",
    "I'm doing this for you, too, you know. To make sure we're both safe. Forever, for good.",
    "That's the spirit, just keep moving forward. And hope the past never catches up to you.", // me everyday
    "As the Vampire Ascendant, I can grant my lover immortality, and bind them to me forever.",
    "My pretty consort, I don't like to see doubt cast upon your face. Fear not: you are mine.",
    "Well that's disturbing. Still better than having an actual conversation with him, though.",
    "Really? I mean, yes, but - really? You'd tell whatever stranger just walked up and asked?",
    "Why not? If I can walk in the sun, you can become all sunshine and roses. I'm sure of it.",
    "I don't think I want you to think of me in terms of sex. I don't know if I want anyone to.",
    "I feel safe with you. Seen. And whatever the future holds for me, I don't want to lose that.",
    "I have to say, you know me better than I thought. I'll have to be more mysterious in future.",
    "Oh I don’t know, I’m sure a vampire spawn could still rip out your throat if he felt like it.",
    "Let me guess - you thought I'd suck blood, but actually I just suck? Was that your witty jab?",
    "If the last day has taught me anything, it's that the impossible is more likely than you think.",
    "Gods, that was close. I could almost kiss the boards here, but - well that would be disgusting.",
    "Of course I will, and you'll drink mine. I can't wait to taste your lips after you've tasted me.",
    "You know, we could always make our own entertainment, darling. Get a little closer, so to speak.",
    "Oh don't bother, not on my account, anyway. Let it roam free. You make quite the pretty pitfiend.",
    "I can hardly blame you. I don't exactly have much to offer right now, beyond new burdens to carry.",
    "Perhaps if we kill this orthon extra bloody, he'll invite us for tea and brandy back in his House.",
    "I should probably start getting used to the shadows again. Who knows how long I have left in the sun?",
    "I had nothing for so long. Nothing. Not even my own body. I will not give it up, now it's mine again.", // :(
    "Excuse me? I'm an eternally young vampire, not your doting grandmother. You can do better. What else?",
    "That's it? We're done with the conversation? I guess we're done with more than just the conversation.",
    "No no - it's not what it looks like, I swear! I wasn't going to hurt you! I just needed - well, blood.",
    "Enjoy yourself, of course, but I dearly hope you aren't only having sex because we haven't in a while.",
    "Maybe it's just hard to see someone else suffer the same thing. It feels unfair - like justice denied.",
    "I used to be agog at everything when I first walked in the sun. Perhaps I'm adjusting to this new life.",
    "The beast you turn into... as charming as it is just make sure those claws don't come anywhere near me.",
    "Shall we have one last night together before you join me in immortality? One for the road, so to speak.",
    "I get all the blame for a gory murder, but I still have to go hungry? Ridiculous. Absolutely ridiculous.",
    "I... I don't know. I can't remember. My face is just some dark shape in my past. Another thing I've lost.",
    "Seven thousand souls have given me the power to carve out my own future, and I want you to be part of it.",
    "Wait, I'm the one you love? Oh no - oh that's so sad. But no, there's absolutely no way this is happening.",
    "Sorry, darling, I haven't got time for underlings. If your boss wants to speak to me, I'm all pointy ears.",
    "Biting flies, midges... Shouldn't nature be beautiful and serene? It looks so nice in the Upper City parks.",
    "Oh you're very sweet. I wouldn't say no to some gory vengeance personally, but that was an adorable answer.",
    "It's... me. The ritual gave me back my reflection - after all these years... Hello again. Gods, I missed you.",
    "You know, for all the sense of dread and horror seeping through this place, I really feel quite at home here.",
    "You could have talked to me before things got murderously bad, you know. We are technically in this together.",
    "I rather thought I was a little slow this time. Usually, they're begging me to drain them on the first night.",
    "I've been dead in the ground for long enough. It's time to try living again. With everything life has to offer.",
    "It's bad enough having one person with fangs trying to keep control of themselves. Two of us could be dangerous.",
    "Why do beautiful people taste better? It hardly seems fair on the ugly - they have such wonderful personalities.",
    "So... I was wondering if maybe - perhaps - you might be able to... Can you read what's on my damned back? Please.",
    "What? You're bowing to this gutter-throated idol? You wretched little worm. I'll show you murder worthy of a god!",
    "This is your chance. Stand with me. Name me your new master. We will get our revenge, and you will all live again.", // YOU LIAR
    "By the hells. Sex, my dear. A night of passion. Not with you, just to be clear. I mean, can you imagine? Urgh. No.",
    "Gods, I never though I'd be so relieved to find a light in the darkness. Or to see so many Harpers clanking about.",
    "Well, apparently there's a limit. Somewhere between a nice summer's day and the full, concentrated power of the sun.",
    "Oh dear, it was a flop? How disappointing. I hope next time you'll have higher standards when it comes to playmates.",
    "I appreciate the thought, truly, but if this is something you want to look into... Well, hearing her out won't kill us.",
    "Well, hello. Looking for a cuddle? Although you don't look entirely... yourself. What's going on in that head of yours?",
    "I want to wake up beside a handsome virgin every morning, but life doesn't give us what we want. Can we kill this 'god' now?",
    "You're too adorable. I'll be fine. I'm sure they'll bring back memories of so many pathetic years, but I'm much stronger now.",
    "No one ever looked out for me. No one ever said a kind thing to me. You're the only one. Other people don't have a heart like you. You're you. No one is like that.", // oh god...
    "It seems you have been dealt a vile hand... I say: play it. Play it for all it's worth. Nobody should deny themselves of their true nature.",
    "Were you actually worried I was angry? Oh you sweet little thing - I'm not going to abandon a feast just because someone else had a nibble.",
    "Haha! That's - oh, you're serious. Well of course we can leave him, it's the easiest thing in the world. We just have to keep on walking.",
    "I don't think poison is for me. Nor stabbing, come to think of it. I've always felt decapitation was a fine choice. One good swing and then - nothing. But we were talking about you. What'll it be?",
    "I spent two hundred years using my body to lure pretty things back for my Master. What I wanted, how I felt about what I was doing, it never mattered. You could have asked me to do the same - to throw myself at her, what I wanted be damned. But you didn't. And I'm grateful.",
    "We are rather excellent together, you know. And united, there is nothing we can't do. I can't say what the future holds for us, but I know we'll be facing it together. And we're going to have a lot of fun.",
    "What a world. I never dreamed I'd be on the paying end in a brothel. But, our leader here has made the dire mistake of failing to sleep with me so far, and it's a mistake I have been aching to correct.",
    "Darling, I was just thinking about you. Remembering our time together, the things we've shared - and I don't just mean that lovely neck of yours. I'm growing to like the whole package, honestly. And you clearly like me too, so...",
    "I know, I'm better than he was. Stronger. Finally free of my past. I'm who I always wanted to be. I have everything I ever wanted.",
    "Are you actually asking me to do this? Trading me for some potion? Because there's something wrong with her blood. I can smell it from here - it's rank.",
    "So far my tadpole and I have been nothing but best friends. Something else is happening to you, isn't it? You have bouts of swooning and swaying, and your jaw is grinding like you're poised to chew off your tongue. Do take care of yourself.",
    "You filthy devil! I'm shocked. I thought the two of you would just flop about like dying fish and then call it a night, but no. Shows me.",
    "This temple certainly is grand. Well, it's a 'run down, bearing the weight of centuries' sort of grand. Which is my favourite kind, incidentally.",
    "What a preposterous question. Vampires can do anything you can do, and a damn sight better. Rich of you to talk about someone else's heart, Karlach.",
    "Is there a reason you're always such an utter drip? Do you have some sort of condition? Honestly, it's like you hate good news.",
    "You know, I never pictured myself as a hero. Never thought I'd be the one they toast for saving so many lives. And now that I'm here... I hate it. This is awful.",
    "Gods... This is the first time in two hundred years I've seen these streets in the sunlight. You can forget just how much colour there is in the world.",
    "You... you are full of surprises, aren't you? Honestly, I have no idea what we're doing. Or what comes next. But I know that this? This is nice.",
    "What in the sweet hells were you thinking, activating that lance? I was right there! Gods, do you have any idea how much that hurt?",
    "No. No, of course, silly of me to even ask. I'll go and find something on four legs to eat, I suppose. See you in the morning.",
    "You know, I never dreamed our noble Jaheira would be such a terrible, terrible mother. It's nice to see heroes are as awful as the rest of us.",
    "I really hoped we could avoid being pawns for a dark god, but here we are, I suppose. I'm with you, my dear. Wherever this leads.",
    "What's not to like? We kill some horrible beastie, and I get what I want in return. Everyone's happy. Except the beastie.",
    "Thank goodness we're all such good, trusting friends, then. On my honour, the only thing on my mind is depraved, carnal lust.",
    "Tonight, I shall drink every drop of your blood. Own your body, kill your mind. It will only hurt a bit, the pleasure will be far greater than the pain.",
    "Ah, drink it in - that sweet, sweet chaos. Not that I approve of goblins, of course filthy little beasts but I do like a good den of debauchery.",
    "So, we have a shapechanger at our camp? Good luck finding her. You could watch out for anyone acting strangely, but... well, you know the lunatics we camp with.",
    "This is what we get for turning our camp into a stopping place for every lost soul in Faerûn. We draw the wrong kind of attention, and then I have to get up and kill these idiots.",
    "After these centuries of torment, I know what you all want. More than power. More than to walk in the sun. You want to see him dead.",
    "Look, I know I have a casual relationship with murder - I don't remember everyone I've killed. But I do remember everyone I've killed in the last five minutes.",
    "Just so you know, I don't judge you for what happened to that bard, Alfira. But the look of guilt on your face was priceless.",
    "I don't know. But isn't it nice? Not to know. You're not a victim. Not a target. Not just one night it's better to forget. But then... whatever in the world could you be?",
    "Hurry, I've got one of those brain things cornered. There, in the grass. You can kill it, can't you? Like you killed the others.",
    "I'm also worried about me, but I seem to somehow be worried about you more. You give me something to care for, and that's worth the peril.",
    "A fine choice! I can think of some nightshades that are deliciously fatal. If they're mixed well, you'll just close your eyes and drift away. And if they're not...",
    "The Rite of Profane Ascension will be mine, and he won't see a scrap of its glory. I am going to complete the ritual as the Ascendant, and then I am going to kill him.",
    "Nothing like a little camp drama to spice up the evening. It's almost a pity things ended so amicably, seeing those two duke it out would be fun.",
    "I am enjoying the latest addition to our little group - Lae'zel is delightful. In a very 'look at me twice and I'll dismember you' kind of way, of course.",
    "Just as the lick of poison is removed from my words of love, yours become a sentence of death. A tragic pair, eh? At least the smut-peddlers of Sharess' Caress will have a field day writing erotic verse about us when we're both dead.",
    "In a thousand years, when I've all but forgotten how to love yet again, you'll flit back into my heart, and I'll weep wondering what happened to my mad love.",
    "Ha! Oh, my love. You can't expect me to kiss that now, can you? No, our kissing days are done, so let's focus on defeating the brain. Otherwise this whole mess will have been for nothing.",
    "I was beginning to believe someone truly wanted me. But I shouldn't have deluded myself. From the start, I was rather counting the hours until it was going to end. Midnight chimes, eh?",
    "Afterwards you felt empty? Alone? Ashamed? It happens, my dear. Best not to dwell on it. Not if you can move on to the next conquest.",
    "Preening in the looking glass? Petty vanity? Of course I miss it. I've never even seen this face. Not since it grew fangs and my eyes turned red.",
    "Are you all right now, or is today a 'I will wed you with a delicate veil of blood blooming over your white curls' kind of day?",
    "Hardly. There's also gold, sex, revenge - quite the list, really. But failing any of those, I will always settle for shallow praise.",
    "I can't even tell if any of you are acting strange because you've been replaced or because this group is full of weirdos!",
    "Well, if you must know--I'm actually a princess of House Nightstar, and I'm married to a tarrasque named Jonathan. Anything else you'd like to know?",
    "It feels ridiculous to still be thinking about Cazador. He's gone, I'm here - I won. But I still keep reliving everything that happened. Playing it over and over in my mind.",
    "Honestly, I was expecting an all-powerful brain to have a lair that was a little flashier. Not immaculately designed or anything, just to have a sense of drama to it.",
    "Come now, don't be coy. Your body's already given you away. I could feel it as I was getting lost in your neck. Your little shakes of excitement. You enjoyed it, didn't you?",
    "Cazador used his tortures to strike terror into me. But I've rarely been more afraid than on the night when I feared Bhaal had claimed you for good. But I trust you won't kill me. And if you do, then I've gotten sloppy and probably have it coming.",
    "Don't you worry. You have supped of my blood. It will be no trouble to extend a fragment of my protection to you. Just don't stray too far. But you'd never dream of doing that, would you?",
    "You were by my side through all of this. Through bloodlust and pain and misery. You were patient. You cared. You trusted me when that was an objectively stupid thing to do.",
    "I know it's you! It's obviously you. I just - I didn't think... Well that's it, isn't it? I didn't think - because if I had for even half a second I would have realised how stupid this was. You were a mistake. But not one I'll be making again.",
    "You know, I feel a connection between us. Like we're two souls walking the same path. Every step we walk trails blood. Killing is an instinct for us. I respect you for that. I would keep the murders in our own camp to a minimum, but otherwise we're very much on the same page.",
    "I can't tell whether you're a bad liar or a worse jester, but either way, it isn't cute. Sorry, sweetheart, but consider our little love affair over. I don't want to be with anyone who has kidnapping fantasies about their partner.",
    "As much as I wish to sequester you in a deep chamber of my palace and keep you all to myself, there's much to be done. First we'll take Baldur's Gate. Then we'll take the world. We'll dominate it until the sun itself melts, and then we'll give ourselves to the night."
];

export { astarionLines };